name: Sync multiple branches
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with: 
          ref: test1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Hi World
          body: Credit new contributors by updating AUTHORS
          branch: test2
